export type ToolbarOptions =
  | "undo"
  | "redo"
  | "bold"
  | "italic"
  | "underline"
  | "strikethrough"
  | "heading"
  | "list"
  | "image"
  | "table"
  | "duplicate-table"
  | "print"
  | "blockquote"
  | "header-footer"
  | "page-size";
